language: php

dist: bionic
sudo: required

addons:
  apt:
    update: true
    packages:
        - gcl
        - build-essential
        - checkinstall
        - coreutils

before_install:
    - sudo apt-get build-dep -y maxima
    - sudo dpkg-reconfigure gcl

before_script:
    - curl -o maxima-5.43.2.tar.gz https://versaweb.dl.sourceforge.net/project/maxima/Maxima-source/5.43.2-source/maxima-5.43.2.tar.gz
    - ls -la .
    - echo "716b4a402abcddf56ca3ac816cd0c9ab17adf16e  maxima-5.43.2.tar.gz" > maxima-5.43.2.tar.gz.sha1sum
    - sha1sum -c maxima-5.43.2.tar.gz.sha1sum
    - tar xfvz maxima-5.43.2.tar.gz
    - cd maxima-5.43.2
    - ./configure --prefix=/usr --exec-prefix=/usr
    - make
    - sudo checkinstall

script:
    - php hi.php
